In [12]:
# Anova test
!pip install statsmodels


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 799.7 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 2.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 3.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB 1.2 MB/s eta 0:00:00a 0:00:01m


In [58]:
import numpy as np
from scipy import stats
import pandas as pd
from scipy.stats import chi2_contingency
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.weightstats import ztest



In [53]:
A = [33,36,39,45,40,37,40,41]
B = [40,41,55,60,52,55,45,49]
C=  [39,43,51,67,50,45,40,52]

In [54]:
print(np.mean(A))
print(np.mean(B))
print(np.mean(C))

38.875
49.625
48.375


In [55]:
group1 = np.array(A)
group2 = np.array(B)
group3 = np.array(C)

In [56]:
f_stat,p_value = stats.f_oneway(group1,group2,group3)

In [57]:
print(f"f_stat = {f_stat} , p_value = {p_value}")

f_stat = 5.700331328997423 , p_value = 0.010531414921334087


In [58]:
alpha = 0.05

In [59]:
if p_value < alpha:
    print("One group mean is different")
else:
    print("No significant difference")

One group mean is different


In [60]:
data = A+B+C

In [61]:
labels = (
    ['group1']*len(A) + 
    ['group2']*len(B) +
    ['group3']*len(C)
)

In [62]:
df = pd.DataFrame(
    {
    "values":data,
    "groups":labels
    }
)

In [63]:
df

,values,groups
0,33,group1
1,36,group1
2,39,group1
3,45,group1
4,40,group1
5,37,group1
6,40,group1
7,41,group1
8,40,group2
9,41,group2


In [64]:
tukey=pairwise_tukeyhsd(endog=df["values"],
                        groups=df["groups"],
                        alpha = 0.05
                       )

In [65]:
print(tukey)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
group1 group2    10.75 0.0148   1.9726 19.5274   True
group1 group3      9.5 0.0324   0.7226 18.2774   True
group2 group3    -1.25 0.9317 -10.0274  7.5274  False
-----------------------------------------------------


In [66]:
print(np.mean(A))
print(np.mean(B))
print(np.mean(C))

38.875
49.625
48.375


In [67]:
# group 1 is a culprit

In [68]:
# Co-relation

In [69]:
x = np.array([1,2,4,6,7,9])
y = np.array([50,55,67,75,80,89])


In [70]:
corr, p_value = stats.pearsonr(x,y)

In [79]:
print(round(corr,3))
print(p_value)

0.998
5.072214302387766e-06


In [80]:
if p_value < 0.05:
    print("Significant linear relationship exist")
else:
    print("No significant linear relationship exist")

Significant linear relationship exist


In [81]:
# Chi square test

In [82]:
table  = np.array([
    [10,20,30],
    [6,9,17]
])

In [84]:
chi2,p,dof,expected= chi2_contingency(table)

In [90]:
print("chi value",round(chi2,3))
print("p_value",round(p,3))
print("degree of freedom",dof)

chi value 0.272
p_value 0.873
degree of freedom 2


In [91]:
print(np.round(expected,2))

[[10.43 18.91 30.65]
 [ 5.57 10.09 16.35]]


In [92]:
alpha = 0.05

In [93]:
if p_value < 0.05:
    print("Significant relationship exist")
else:
    print("No significant relationship exist")

Significant relationship exist


In [102]:
n=table.sum()
k = min(table.shape)

In [103]:
cramers_v = np.sqrt(chi2/(n*(k-1)))
print(cramers_v)

0.05433137570422292


In [104]:
if cramers_v < 0.1:
    print("Very Weak")
elif cramers_v < 0.3:
    print("Weak")
elif cramers_v < 0.5:
    print("Moderate")
else:
    print("Strong")

Very Weak


In [105]:
x = np.array([1,2,4,6,7,9])
y = np.array([50,55,67,75,80,89])

In [106]:
slope,intercept,r_value,p_value,std_err = stats.linregress(x,y)

In [110]:
new_x = int(input())
predicted_y= intercept + slope*new_x
print(predicted_y)

 7


79.89679715302492


In [111]:
# Outliers

In [144]:
data = np.array([50,55,67,75,80,89,200,250])

In [145]:
q1=np.percentile(data,25)
q3=np.percentile(data,75)

In [146]:
iqr = (q3-q1)

In [147]:
print(q1,q3,iqr)

64.0 116.75 52.75


In [148]:
lower_bound = q1-1.5*iqr
upper_bound = q3+1.5*iqr

In [149]:
print(f"lower bound = {lower_bound}, upper bound = {upper_bound}")

lower bound = -15.125, upper bound = 195.875


In [150]:
outliers = data[(data<lower_bound) | (data > upper_bound)]

In [151]:
print(outliers)

[200 250]


In [152]:
# ouliers Z_score

In [153]:
z_scores = stats.zscore(data)

In [154]:
z_scores

array([-0.83733354, -0.76545942, -0.59296152, -0.47796292, -0.4060888 ,
       -0.27671538,  1.31889017,  2.0376314 ])

In [155]:
outliers = data[np.abs(z_scores)>2]

In [156]:
outliers


array([250])

In [157]:
median = np.median(data)

In [158]:
mad = np.median(np.abs(data-median))


In [159]:
mad

np.float64(17.0)

In [160]:
modified_zscores = 0.6754*(data-median)/mad

In [161]:
modified_zscores

array([-1.09255882, -0.89391176, -0.41715882, -0.09932353,  0.09932353,
        0.45688824,  4.86685294,  6.85332353])

In [162]:
outliers = data[np.abs(modified_zscores) > 3.5]

In [163]:
outliers

array([200, 250])

In [1]:
# Practice

In [2]:
# one sample T-test : when you want to compare sample mean vs population mean

In [9]:
data = [45,48,50,52,47]
mu_0 = 55 
# mu_0 is population mean

In [10]:
t_stat,p_value=stats.ttest_1samp(data,mu_0)

In [11]:
print(f"t_stat={t_stat} , p_value={p_value}")

t_stat=-5.46219886477563 , p_value=0.005462307160278639


In [12]:
if p_value < 0.05:
    print("significant difference")
else:
    print("no significant difference")

significant difference


In [13]:
# independent t-test: when we have two different groups eg: boys marks vs girls marks

In [14]:
A = [50, 55, 53, 52, 54]
B = [60, 62, 58, 59, 61]

In [15]:
t_stat,p_value = stats.ttest_ind(A,B)

In [16]:
print(f"t_stat={t_stat} , p_value={p_value}")

t_stat=-6.465790872963899 , p_value=0.00019502272710454155


In [17]:
if p_value < 0.05:
    print("significant difference")
else:
    print("no significant difference")

significant difference


In [18]:
# paired t-test : same group before and after

In [23]:
before =[40,45,42,38,41]
after=[50,55,52,48,49]

In [24]:
t_stat,p_value= stats.ttest_rel(before,after)

In [25]:
print(f"t_stat={t_stat} , p_value={p_value}")

t_stat=-24.0 , p_value=1.7877071517340862e-05


In [26]:
if p_value < 0.05:
    print("significant difference")
else:
    print("no significant difference")

significant difference


In [27]:
# Anova test : used to compare 3 or more groups 

In [28]:
A = [40,42,41]
B = [55,57,56]
C = [48,50,47]

In [30]:
f_stat,p_value=stats.f_oneway(A,B,C)

In [31]:
print(f"t_stat={t_stat} , p_value={p_value}")

t_stat=-24.0 , p_value=1.5685250576440666e-05


In [32]:
if p_value < 0.05:
    print("significant difference")
else:
    print("no significant difference")

significant difference


In [33]:
# tukey test apply on above to check which group differs from which

In [34]:
# combine all data into one list
data = A+ B + C

In [35]:
# create a group labels
groups = (["A"]*len(A) + 
          ["B"]*len(B) + 
          ["C"]*len(C)
         )

In [36]:
groups

['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C']

In [37]:
tukey = pairwise_tukeyhsd(endog=data,
                          groups=groups,
                          alpha = 0.05)

In [39]:
print(tukey)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     A      B     15.0    0.0  11.9891 18.0109   True
     A      C   7.3333 0.0007   4.3224 10.3443   True
     B      C  -7.6667 0.0006 -10.6776 -4.6557   True
-----------------------------------------------------


In [40]:
# conclusion : All three groups are significantly different from each other.
# There is no pair that is similar.

In [41]:
# chi- square test: tells categorical data relationship

In [42]:
# product like and dislike
male = [20,15]
female=[30,35]
data = np.array([
    [20,15],
    [30,35]
])

In [43]:
chi_stat,p_value,dof,expected = stats.chi2_contingency(data)

In [44]:
print("Chi-square value:", chi_stat)
print("p-value:", p_value)
print("Degree of freedom:", dof)
print("Expected Frequencies:\n", expected)

Chi-square value: 0.7032967032967032
p-value: 0.4016781664697727
Degree of freedom: 1
Expected Frequencies:
 [[17.5 17.5]
 [32.5 32.5]]


In [46]:
if p_value < 0.05:
    print("Significant relationship (Reject H0)")
else:
    print("No significant relationship (Accept H0)")
#here is no significant association between Gender and Product Preference.
    

No significant Association (Accept H0)


In [47]:
 # Gender does not affect liking/disliking of the product.

In [48]:
# correlation test : checks relationship b/w two numerical variables

In [49]:
hours = [2,4,6,8,10]
marks = [20,40,50,65,80]
 

In [50]:
corr,p_value = stats.pearsonr(hours,marks)

In [51]:
print("correlation:",corr)
print("p_value:",p_value)

correlation: 0.9958640886279954
p_value: 0.0003190957935936728


In [52]:
if p_value < 0.05:
    print("significant difference")
else:
    print("no significant difference")

significant difference


In [53]:
# Z-Test: used when sample size is larger and population std deviation is known

In [60]:
data = [52,54,51,53,55,56,50,52,54,53,
        51,52,53,55,54,52,53,51,56,57,
        54,53,52,55,54,53,52,51,56,55,
        53,52,54,55,53,52,51,54,55,56]
mu_0 = 50

In [61]:
z_stat,p_value = ztest(data,value = mu_0)

In [62]:
print("z-staticstic",z_stat)
print("p_value",p_value)

z-staticstic 12.333020244771747
p_value 6.014918017329417e-35


In [63]:
if p_value < 0.05:
    print("Significant Difference (Reject H0)")
else:
    print("No Significant Difference (Accept H0)")

Significant Difference (Reject H0)


In [64]:
# outliers: A value which is too far away from the rest of the data


In [65]:
# Z-score method to detect ouliers
# z-score tells How many standard deviations a data point is away from the mean

In [91]:
data = [10,12,11,13,140,15,16,17,18,19,100,120]

In [92]:
z_scores = stats.zscore(data)

In [93]:
print(z_scores)

[-0.66549146 -0.6224408  -0.64396613 -0.60091547  2.13280148 -0.55786481
 -0.53633948 -0.51481415 -0.49328882 -0.47176349  1.27178826  1.70229487]


In [94]:
# find outliers
outliers = []
for i in range(len(z_scores)):
    if abs(z_scores[i]) > 2:
        outliers.append(data[i])
print("outliers",outliers)

outliers [140]


In [96]:
# Modified z-score: best for multiple outliers 
# it uses median instead of mean 
# MAD(median absolute deviation)

In [97]:
data = np.array([10,12,11,13,14,15,16,17,18,19,100,120])

In [98]:
median = np.median(data)

In [99]:
mad = np.median(np.abs(data-median))

In [100]:
mod_z = 0.6745 *(data-median)/mad

In [101]:
mod_z

array([-1.23658333, -0.78691667, -1.01175   , -0.56208333, -0.33725   ,
       -0.11241667,  0.11241667,  0.33725   ,  0.56208333,  0.78691667,
       18.99841667, 23.49508333])

In [102]:
outliers = data[np.abs(mod_z) > 3.5]

In [103]:
print("outliers",outliers)

outliers [100 120]
